version: 2.1

executors:
  linux:
    docker:
      - image: ubuntu:24.04

jobs:
  build:
    executor: linux
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Debug project structure
          command: |
            pwd
            ls -la
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y g++ cmake libsfml-dev
      - run:
          name: Debug project structure
          command: |
            pwd
            ls -la
      - run:
          name: Build Project
          command: |
            cmake -S . -B build
            cmake --build build

  test:
    executor: linux
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y g++ cmake libsfml-dev
      - run:
          name: Run Hello World Test
          command: |
            mkdir -p build                                           
            cd build
            cmake ..
            cmake --build .
            OUTPUT=$(./Pacman)
            if [ "$OUTPUT" = "Hello World" ]; then
            echo "✅ Output matched: $OUTPUT"
            else
            echo "❌ Expected 'Hello World' but got: '$OUTPUT'"
            exit 1
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build