version: 2.1

executors:
  linux:
    docker:
      - image: ubuntu:24.04

jobs:
  build:
    executor: linux
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Debug project structure
          command: |
            pwd
            ls -la
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y g++ cmake libsfml-dev
      - run:
          name: Build Project
          command: |
            cmake -S . -B build
            cmake --build build
            if [ $? -ne 0 ]; then
              echo "Build failed!"
              exit 1
            else
              echo "Build succeeded!"
            fi

  test:
    executor: linux
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y g++ cmake libsfml-dev
      - run:
          name: Test Build and Ensure Exit Code 0
          command: |
            mkdir -p build
            cd build
            cmake ..
            cmake --build .
            if [ $? -ne 0 ]; then
              echo "Test build failed!"
              exit 1
            else
              echo "Test build succeeded and returned 0!"
              exit 0
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build